### ISSUE TITLE
Unauthorized on resource deletion in EKS

### ISSUE THREAD

**Issue by nikitazernov** [hashicorp/terraform-provider-kubernetes#1113]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 0.14.4
Kubernetes provider version: 1.13.3
Kubernetes version: 1.18
```

### Affected Resource(s)

All resources

### Terraform Configuration Files
```hcl
resource "kubernetes_service" "admin-panel" {
  metadata {
    name = "admin-panel"
    namespace = kubernetes_namespace.platform.id
  }
  spec {
    selector = {
      app = "admin-panel"
    }
    port {
      protocol = "TCP"
      port = 80
    }
  }
}

resource "kubernetes_ingress" "admin-panel" {
  depends_on = [helm_release.nginx-ingress, aws_route53_record.nginx, helm_release.cert-manager]

  metadata {
    name = "admin-panel-ingress"
    namespace = kubernetes_namespace.platform.id
    annotations = {
      "kubernetes.io/ingress.class" = "nginx"
      "acme.cert-manager.io/http01-edit-in-place" = "true"
      "cert-manager.io/cluster-issuer" = "letsencrypt"
      "cert-manager.io/issue-temporary-certificate" = "true"
      "nginx.ingress.kubernetes.io/configuration-snippet" = <<-EOT
        proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
        grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      EOT
    }
  }
  spec {
    rule {
      host = "panel.adm.${var.admin_zone}"
      http {
        path {
          backend {
            service_name = "admin-panel"
            service_port = 80
          }
        }
      }
    }
  }
}
```

### Debug Output

https://gist.github.com/nikitazernov/282139c480c47f2a7df47ed846b1f774

### Steps to Reproduce

1. terraform apply
2. terraform destroy

### Expected Behaviour

1. On apply all resources created successfully
2. On destroy all resources deleted successfully

### Actual Behaviour

1. On apply all resources created successfully
2. On destroy all resources are failed to delete because unauthorized

### Important Factoids

Cluster is running on AWS EKS. Resource deletion using `kubectl` with the same AWS credentials is successful.
Here are snippets from EKS logs:
https://gist.github.com/nikitazernov/6db450ac4b10d2779c571fe0281c1852
The user is empty on deletion, but persists in all other requests.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by thpang** [comment]
@nikitazernov what did you do to fix this issue? I am seeing this as well. No explanation here on what was fixed.

**Comment by nikitazernov** [comment]
@thpang hello! Later I've figured out this issue appeared after update to terraform 0.14. After downgrading Terraform to 0.13.5 it worked.

**Comment by thpang** [comment]
Yes I have come to the same conclusion, that moving back to tf 0.13.6 works, but that tf 0.14.4 does not. Have not turned on tf debugging to capture more. Hopefully someone from Hashicorp will pick this up.

**Comment by TsvetanMilanov** [comment]
The problem seems to be in terraform, not in the kubernetes provider - https://github.com/hashicorp/terraform/issues/27172
The fix is merged but terraform 0.14.5 still reproduces the issue. I guess it is not released yet. However, the workaround with manually refreshing the state before destroying, worked for me.

**Comment by eaterm** [comment]
Have the same issue. Running refresh before destroy seemed to work.
But looking at the output of the log data sources are still not refreshed.

Looks like aws_eks_cluster_auth is not refreshing. During destroy (even with a refresh before) and and plan/apply.

**Comment by dak1n1** [comment]
This is unfortunately a common problem when EKS credentials expire and the Kubernetes provider attempts to initialize using the outdated credentials. See this comment for more details and a work-around. https://github.com/hashicorp/terraform-provider-kubernetes/issues/1131#issuecomment-776326103

**Comment by derjust** [comment]
> The fix is merged but terraform 0.14.5 still reproduces the issue. I guess it is not released yet. However, the workaround with manually refreshing the state before destroying, worked for me.

The fix is announced only in the changelog of the (upcoming) [v0.15.0](https://github.com/hashicorp/terraform/releases/tag/v0.15.0-alpha20210210) release

**Comment by dak1n1** [comment]
Closing since it's fixed upstream.

**Comment by thpang** [comment]
Just as a side note, given this issue was not fixed at all in v0.14.x this is going to cause folks that need this functionality to completely skip the v0.14.x of terraform for their work. I know we will ;)
